server:
  port: 8100
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: pp-route
          uri: http://localhost:8080/
          predicates:
            - Path=/pp/**